### ISSUE TITLE
Add option to turn off ajax call

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#127]
Research adding a setting to turn off ajax. 

ref: https://secure.helpscout.net/conversation/638064316/258495?folderId=956509
https://wordpress.org/support/topic/disable-and-or-reduce-usage-via-ajax-call-ck_add_user_visit/

**Comment by tnorthcutt** [comment]
Update when fixed: https://secure.helpscout.net/conversation/657338201/269247?folderId=2569250

**Comment by tnorthcutt** [comment]
Currently our AJAX call happens on [every page load](https://github.com/ConvertKit/ConvertKit-WordPress/blob/15213d293f481bee40e582c366318db2fbf71152/resources/frontend/wp-convertkit.js#L11-L25) regardless of if there is a subscriber ID available. We should optimize this as a first step since that'll help everyone.

We can also add a toggle for edge cases.

**Comment by tnorthcutt** [comment]
Would also be great if we could only trigger tag attempts on a page/post with tags set.

**Comment by tnorthcutt** [comment]
Closed in https://github.com/ConvertKit/ConvertKit-WordPress/pull/162
