### ISSUE TITLE
Support php 7.0

### ISSUE THREAD

**Issue by menasheh** [ConvertKit/ConvertKit-WordPress#40]
I notice that you're building for php 5.3, but not 7.0.  

Please fix that?

**Comment by annedorko** [comment]
Chiming in with a "please address this", I just switched over to PHP 7.0 and this plugin no longer works!

**Comment by growdev** [comment]
I've tested with PHP 7.0 and the plugin works as expected.
Are there any specific errors that you are encountering with PHP 7.0?

**Comment by annedorko** [comment]
Hi Daniel,

I haven’t retested since my comment a little while back so I’m not sure if
there’s a new update to the plugin. I didn’t do extensive testing because I
was busy, but it essentially stopped the output of my page wherever the
ConvertKit plugin was supposed to appear – the only significant change was
that I moved to a PHP 7.0 server. It’s possible there was another error but
I am not sure what to look for.

Cheers,
Anne

On 26 December 2016 at 11:13:49, Daniel Espinoza (notifications@github.com)
wrote:

I've tested with PHP 7.0 and the plugin works as expected.
Are there any specific errors that you are encountering with PHP 7.0?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ConvertKit/ConvertKit-WordPress/issues/40#issuecomment-269235664>,
or mute the thread

**Comment by menasheh** [comment]
@growdev Where would we look for these errors?  The plugin just said can't connect to the API, and the error log did not have any useful information.  It was the same message repeated over and over again, and it looked like the important part that was supposed to be logged wasn't being logged properly; the log only had that a particular method was run.

**Comment by growdev** [comment]
If the plugin can't connect to the API then that's a host level issue. Best to check with your webhost to see if they block outgoing connections.
